### ISSUE TITLE
How this one works?

### ISSUE THREAD

**Issue by satrianivzla** [bkader/ci-theme#1]
First sorry to ask that kind of basic question.
But I am trying to loading your theme script and If I added as a library or a Helper didn't work

**Comment by bkader** [comment]
Hi, sorry for being late.
Simply drop the files where they should be (like they are inside the package) than load the Theme library.
All you have to do after is to create your views and use available methods.
Let me know if all works.

**Comment by satrianivzla** [comment]
Hi bkader
Don't worry I found the way to use your source later to post the comment here that was the reason why I closed the issue 
Thank you for your kind answer!
Greetings!
